Repository edgefund/edgefund-core, pull requests merged in 2018-08, with the labels that each got.

#27 Complete the testing for the CoinToss Contract (closes #26)
  .gitignore
  .travis.yml
  contracts/CoinToss.sol
  contracts/CoinTossMock.sol
  coverage.json
  package.json
  test/TestCoinToss.js
  test/TestEVs.sol
  test/helpers/throwHandler.js
Labels: enhancement, testing

#33 Use Open Zeppelin test helpers.
  README.md
  assets/EdgeFundNew.png
  package-lock.json
  package.json
  test/TestCoinToss.js
  test/TestHelpers.js
  test/helpers/delorean.js
Labels: testing

#35 Continuous Deploy to Rinkeby Test Network
  .travis.yml
  LICENSE
  deploy.sh
  migrations/1_initial_migration.js
  migrations/2_deploy_edgefund.js
  migrations/3_deploy_cointoss.js
  package-lock.json
  package.json
  truffle.js
Labels: enhancement
